### ISSUE TITLE
How to remove the white edge of window?

### ISSUE THREAD

**Issue by Poker-sang** [castorix/WinUI3_SwapChainPanel_Layered#1]
When I create a resizable, transparent window, there is always a white edge on the top of the window. Anyway to remove it while keeping the window border and resizing function?

btw, I commented `_presenter.IsResizable = false`, and then the border would not be removed by `_presenter.SetBorderAndTitleBar` (see also [issue7629](https://github.com/microsoft/microsoft-ui-xaml/issues/7629)). Is there any P/Invoke method to resolve this?

![BBP%9F2 M% G{B )7H4D~)5](https://user-images.githubusercontent.com/62325494/212528329-c0103f53-e933-4b56-b2f9-95b0e18033a2.png)

**Comment by castorix** [comment]
It is because of DWM
DWM can be removed with DWMWA_NCRENDERING_POLICY but you will get the old big resizing borders
Otherwise, you can see threads on Google with _DwmExtendFrameIntoClientArea_  like https://stackoverflow.com/questions/39731497/create-window-without-titlebar-with-resizable-border-and-without-bogus-6px-whit
but I did not test with WinUI 3...

**Comment by Poker-sang** [comment]
> It is because of DWM DWM can be removed with DWMWA_NCRENDERING_POLICY but you will get the old big resizing borders Otherwise, you can see threads on Google with _DwmExtendFrameIntoClientArea_ like https://stackoverflow.com/questions/39731497/create-window-without-titlebar-with-resizable-border-and-without-bogus-6px-whit but I did not test with WinUI 3...

Thank you! But I tested the code in WinUI3 and failed... Perhaps I misunderstood some points.

I found that when setting `_presenter.IsResizable = false`, I can still only resize the window from the white edge side, the left, right and bottom side are maybe too thin to grip and resize?

And if I write this way:
```cs
long nExStyle = GetWindowLong(hWndMain, GWL_EXSTYLE);
if ((nExStyle & WS_EX_LAYERED) == 0)
{
    SetWindowLong(hWndMain, GWL_EXSTYLE, (IntPtr)(nExStyle | WS_EX_LAYERED));
    // other code in this region is deleted
}
// _presenter property setting is moved under here
_presenter = _apw.Presenter as Microsoft.UI.Windowing.OverlappedPresenter;
_presenter.IsResizable = false;
_presenter.SetBorderAndTitleBar(false, false);
```
The white edge disappeared, but we cannot use resize and snap fonction now.

Resizing is easy to implement, but I don't know how to trigger or response Snap Shortcut(Drag title bar to the edge of screen and snap) in Win11? I hope I'm not bothering you XD

![A M`EMLY8I0VNZRO6XX1$D2](https://user-images.githubusercontent.com/62325494/213210624-1f34127a-279d-4296-9bfe-ec98de7a7fe1.png)

**Comment by castorix** [comment]
I don't know about snapping.
I have only Windows 10; from my tests, snapping works in a C++/Win32 app with WS_OVERLAPPEDWINDOW style (+ WS_VISIBLE) on a Layered window, but then I tested the same style with WinUI 3 and it did not work at all...

**Comment by Poker-sang** [comment]
> I don't know about snapping. I have only Windows 10; from my tests, snapping works in a C++/Win32 app with WS_OVERLAPPEDWINDOW style (+ WS_VISIBLE) on a Layered window, but then I tested the same style with WinUI 3 and it did not work at all...

Thank you!! I used to hear that to enable snap layout, we should response [`WM_NCHITTEST`](https://learn.microsoft.com/windows/apps/desktop/modernize/apply-snap-layout-menu) event and return `HTMAXBUTTON`. So, I thought maybe snap short cut (or mouse snap) may be implemented in the similar way? I will try it later.

**Comment by qjl1569** [comment]
> > It is because of DWM DWM can be removed with DWMWA_NCRENDERING_POLICY but you will get the old big resizing borders Otherwise, you can see threads on Google with _DwmExtendFrameIntoClientArea_ like https://stackoverflow.com/questions/39731497/create-window-without-titlebar-with-resizable-border-and-without-bogus-6px-whit but I did not test with WinUI 3...
> 
> Thank you! But I tested the code in WinUI3 and failed... Perhaps I misunderstood some points.
> 
> I found that when setting , I can still only resize the window from the white edge side, the left, right and bottom side are maybe too thin to grip and resize?`_presenter.IsResizable = false`
> 
> And if I write this way:
> 
> ```cs
> long nExStyle = GetWindowLong(hWndMain, GWL_EXSTYLE);
> if ((nExStyle & WS_EX_LAYERED) == 0)
> {
>     SetWindowLong(hWndMain, GWL_EXSTYLE, (IntPtr)(nExStyle | WS_EX_LAYERED));
>     // other code in this region is deleted
> }
> // _presenter property setting is moved under here
> _presenter = _apw.Presenter as Microsoft.UI.Windowing.OverlappedPresenter;
> _presenter.IsResizable = false;
> _presenter.SetBorderAndTitleBar(false, false);
> ```
> 
> The white edge disappeared, but we cannot use resize and snap fonction now.
> 
> Resizing is easy to implement, but I don't know how to trigger or response Snap Shortcut(Drag title bar to the edge of screen and snap) in Win11? I hope I'm not bothering you XD
> 
> ![A M`EMLY8I0VNZRO6XX1$D2](https://user-images.githubusercontent.com/62325494/213210624-1f34127a-279d-4296-9bfe-ec98de7a7fe1.png)

Here is an example to remove the title block and keep the resizing border

[https://github.com/qjl1569/winui3-samples](https://github.com/qjl1569/winui3-samples)

**Comment by Poker-sang** [comment]
> Here is an example to remove the title block and keep the resizing border
> 
> https://github.com/qjl1569/winui3-samples

Thank you! It looks nice. But I want to keep the SwapChainPanel and transparent background, they looks like cannot be both. And better implement snap layout and snap short cut. Do you have any ideas?

**Comment by qjl1569** [comment]
> > Here is an example to remove the title block and keep the resizing border
> > https://github.com/qjl1569/winui3-samples
> 
> Thank you! It looks nice. But I want to keep the SwapChainPanel and transparent background, they looks like cannot be both. And better implement snap layout and snap short cut. Do you have any ideas?

Transparent background needs to add to the window WS_ EX_ NOREDIRECTIONBITMAP extends the style and removes the mandatory background added in the composition window. I think this needs to be fixed by the Microsoft team.
Snapshot layout only needs to be set in Calculate the coordinates in the WM_ NCHITTEST message and return HTMAXBUTTON.
![1](https://user-images.githubusercontent.com/27790417/219983092-6729e41c-3410-42f0-b343-833fa40bedb7.png)

**Comment by Poker-sang** [comment]
> Transparent background needs to add to the window WS_ EX_ NOREDIRECTIONBITMAP extends the style and removes the mandatory background added in the composition window. I think this needs to be fixed by the Microsoft team.
> Snapshot layout only needs to be set in Calculate the coordinates in the WM_ NCHITTEST message and return HTMAXBUTTON.
> ![1](https://user-images.githubusercontent.com/27790417/219983092-6729e41c-3410-42f0-b343-833fa40bedb7.png)
> 

Thanks, I learnt a lot! And how about snap shortcut? That is to say, when dragging the window to the edge of the screen, the window automatically snaps?
